package com.example.kala.navigation

const val HOME_SCREEN_ROUTE = "homeScreen"
const val OPTION_SCREEN_ROUTE = "optionScreen"
const val HELP_SCREEN_ROUTE = "helpScreen"
const val LANGUAGE_SCREEN_ROUTE = "languageScreen"
const val ADD_EXCHANGE_SCREEN_ROUTE = "addExchangeScreen"
const val RECORD_SCREEN_ROUTE = "recordScreen"
const val ABOUT_EXCHANGE_SCREEN_ROUTE = "aboutExchangeScreen"
const val EDIT_EXCHANGE_SCREEN_ROUTE = "editExchangeScreen"
const val REPORT_SCREEN_ROUTE = "reportScreen"
const val ABOUT_MONTH_SCREEN_ROUTE = "aboutMonthScreen"
const val MAIN_SCREEN_ROUTE = "mainScreen"
const val SIGN_UP_SCREEN_ROUTE = "signUpScreen"
const val LOG_IN_SCREEN_ROUTE = "logInScreen"
const val CHANGE_PASS_SCREEN_ROUTE = "changePassScreen"
