package com.example.kala.ui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class Dimens(
    //Height
    val height0: Dp = 0.dp,
    val height1: Dp = 0.dp,
    val height2: Dp = 0.dp,
    val height3: Dp = 0.dp,
    val height4: Dp = 0.dp,
    val height5: Dp = 0.dp,
    val heightBigTextInput: Dp = 0.dp,
    val heightGraph: Dp = 0.dp,
    val heightSummaryScope: Dp = 0.dp,
    val heightSummaryRow: Dp = 0.dp,
    val heightCard: Dp = 0.dp,
    val heightPieChartInfo: Dp = 0.dp,
    val heightBarChartInfo: Dp = 0.dp,
    val heightHelp: Dp = 0.dp,
    //Image
    val imageAboutMonth: Dp = 0.dp,
    val imageMenuInput: Dp = 0.dp,
    val imageLargeButton: Dp = 0.dp,
    val image3: Dp = 0.dp,
    val image4: Dp = 0.dp,
    val imageSmallButton: Dp = 0.dp,
    val widthNone: Dp = 0.dp,
    val widthBarChartInfo: Dp = 0.dp,
    val widthAboutExchange: Dp = 0.dp,
    val widthMediumButton: Dp = 0.dp,
    val widthCard: Dp = 0.dp,
    val widthCardColumn: Dp = 0.dp,
    val widthInput: Dp = 0.dp,
    val width6: Dp = 0.dp,
    val widthMessage: Dp = 0.dp,
    val width8: Dp = 0.dp,
    val widthChartInfo: Dp = 0.dp,
    //Others
    val rounded: Dp = 0.dp,
    val shadow: Dp = 0.dp,
    val border: Dp = 0.dp,
    //Space
    val space0: Dp = 0.dp,
    val space1: Dp = 0.dp,
    val space2: Dp = 0.dp,
    val space3: Dp = 0.dp,
    val space4: Dp = 0.dp,
    //FontSize
    val fontSize0: TextUnit = 0.sp,
    val fontSize1: TextUnit = 0.sp,
    val fontSize2: TextUnit = 0.sp,
    val fontSize3: TextUnit = 0.sp,
    val fontSizeHeader: TextUnit = 0.sp,
    val fontSizeTitle: TextUnit = 0.sp,
    val fontSizeLogo: TextUnit = 0.sp,
    val fontSizeSummaryRow: TextUnit = 0.sp,
    val fontSizeMoney: TextUnit = 0.sp,
    val fontSizeDate: TextUnit = 0.sp,
    val fontSizeDescription: TextUnit = 0.sp,
    //Padding
    val padding0: Dp = 0.dp,
    val padding1: Dp = 0.dp,
    val padding2: Dp = 0.dp,
    val padding3: Dp = 0.dp,
    val padding4: Dp = 0.dp,
    val padding5: Dp = 0.dp,
    val paddingHeaderFooter: Dp = 0.dp,
    //Size
    val sizeLogoSmall: Dp = 0.dp,
    val sizeLogoBig: Dp = 0.dp,
)

val SmallPhone = Dimens(
    //Height
    height0 = 25.dp,
    height1 = 40.dp,
    height2 = 50.dp,
    height3 = 60.dp,
    height4 = 100.dp,
    height5 = 100.dp,
    heightBigTextInput = 150.dp,
    heightGraph = 150.dp,
    heightSummaryScope = 150.dp,
    heightSummaryRow = 40.dp,
    heightCard = 75.dp,
    heightPieChartInfo = 200.dp,
    heightBarChartInfo = 270.dp,
    heightHelp = 400.dp,
    //Image
    imageAboutMonth = 20.dp,
    imageMenuInput = 35.dp,
    imageLargeButton = 30.dp,
    image3 = 40.dp,
    image4 = 50.dp,
    imageSmallButton = 80.dp,
    //Width
    widthNone = 0.dp,
    widthBarChartInfo = 90.dp,
    widthAboutExchange = 125.dp,
    widthMediumButton = 130.dp,
    widthCard = 260.dp,
    widthCardColumn = 130.dp,
    widthInput = 200.dp,
    width6 = 225.dp,
    widthMessage = 230.dp,
    width8 = 270.dp,
    widthChartInfo = 300.dp,
    //Others
    rounded = 7.dp,
    shadow = 7.dp,
    border = 1.dp,
    //Space
    space0 = 5.dp,
    space1 = 7.dp,
    space2 = 10.dp,
    space3 = 12.dp,
    space4 = 15.dp,
    //FontSize
    fontSize0 = 13.sp,
    fontSize1 = 17.sp,
    fontSize2 = 20.sp,
    fontSize3 = 22.sp,
    fontSizeHeader = 30.sp,
    fontSizeTitle = 30.sp,
    fontSizeLogo = 45.sp,
    fontSizeSummaryRow = 20.sp,
    fontSizeMoney = 25.sp,
    fontSizeDate = 15.sp,
    fontSizeDescription = 15.sp,
    //Padding
    padding0 = 2.dp,
    padding1 = 6.dp,
    padding2 = 7.dp,
    padding3 = 6.dp,
    padding4 = 10.dp,
    padding5 = 15.dp,
    paddingHeaderFooter = 30.dp,
    //Size
    sizeLogoSmall = 125.dp,
    sizeLogoBig = 175.dp,
)

val MediumPhone = Dimens(
    //Height
    height0 = 40.dp,
    height1 = 50.dp,
    height2 = 60.dp,
    height3 = 80.dp,
    height4 = 100.dp,
    height5 = 150.dp,
    heightBigTextInput = 180.dp,
    heightGraph = 200.dp,
    heightSummaryScope = 210.dp,
    heightSummaryRow = 40.dp,
    heightCard = 100.dp,
    heightPieChartInfo = 300.dp,
    heightBarChartInfo = 345.dp,
    heightHelp = 500.dp,
    //Image
    imageAboutMonth = 30.dp,
    imageMenuInput = 35.dp,
    imageLargeButton = 40.dp,
    image3 = 50.dp,
    image4 = 60.dp,
    imageSmallButton = 100.dp,
    //Width
    widthNone = 0.dp,
    widthBarChartInfo = 90.dp,
    widthAboutExchange = 125.dp,
    widthMediumButton = 130.dp,
    widthCard = 280.dp,
    widthCardColumn = 140.dp,
    widthInput = 230.dp,
    width6 = 250.dp,
    widthMessage = 280.dp,
    width8 = 300.dp,
    widthChartInfo = 320.dp,
    //Others
    rounded = 10.dp,
    shadow = 10.dp,
    border = 2.dp,
    //Space
    space0 = 5.dp,
    space1 = 10.dp,
    space2 = 15.dp,
    space3 = 20.dp,
    space4 = 50.dp,
    //FontSize
    fontSize0 = 20.sp,
    fontSize1 = 25.sp,
    fontSize2 = 25.sp,
    fontSize3 = 30.sp,
    fontSizeHeader = 34.sp,
    fontSizeTitle = 35.sp,
    fontSizeLogo = 50.sp,
    fontSizeSummaryRow = 20.sp,
    fontSizeMoney = 30.sp,
    fontSizeDate = 20.sp,
    fontSizeDescription = 17.sp,
    //Padding
    padding0 = 5.dp,
    padding1 = 7.dp,
    padding2 = 8.dp,
    padding3 = 10.dp,
    padding4 = 15.dp,
    padding5 = 20.dp,
    paddingHeaderFooter = 30.dp,
    //Size
    sizeLogoSmall = 150.dp,
    sizeLogoBig = 200.dp,
)

val LargePhone = Dimens(
    //Height
    height0 = 40.dp,
    height1 = 50.dp,
    height2 = 60.dp,
    height3 = 80.dp,
    height4 = 100.dp,
    height5 = 175.dp,
    heightBigTextInput = 180.dp,
    heightGraph = 225.dp,
    heightSummaryScope = 250.dp,
    heightSummaryRow = 50.dp,
    heightCard = 100.dp,
    heightPieChartInfo = 300.dp,
    heightBarChartInfo = 370.dp,
    heightHelp = 600.dp,
    //Image
    imageAboutMonth = 35.dp,
    imageMenuInput = 35.dp,
    imageLargeButton = 40.dp,
    image3 = 50.dp,
    image4 = 60.dp,
    imageSmallButton = 110.dp,
    //Width
    widthNone = 0.dp,
    widthBarChartInfo = 90.dp,
    widthAboutExchange = 125.dp,
    widthMediumButton = 150.dp,
    widthCard = 300.dp,
    widthCardColumn = 150.dp,
    widthInput = 280.dp,
    width6 = 250.dp,
    widthMessage = 300.dp,
    width8 = 362.dp,
    widthChartInfo = 350.dp,
    //Others
    rounded = 10.dp,
    shadow = 10.dp,
    border = 2.dp,
    //Space
    space0 = 7.dp,
    space1 = 12.dp,
    space2 = 18.dp,
    space3 = 22.dp,
    space4 = 50.dp,
    //FontSize
    fontSize0 = 20.sp,
    fontSize1 = 25.sp,
    fontSize2 = 28.sp,
    fontSize3 = 30.sp,
    fontSizeHeader = 34.sp,
    fontSizeTitle = 35.sp,
    fontSizeLogo = 55.sp,
    fontSizeSummaryRow = 20.sp,
    fontSizeMoney = 30.sp,
    fontSizeDate = 20.sp,
    fontSizeDescription = 20.sp,
    //Padding
    padding0 = 3.dp,
    padding1 = 7.dp,
    padding2 = 8.dp,
    padding3 = 10.dp,
    padding4 = 15.dp,
    padding5 = 20.dp,
    paddingHeaderFooter = 30.dp,
    //Size
    sizeLogoSmall = 175.dp,
    sizeLogoBig = 225.dp,
)

val Tablet = Dimens(
    //Height
    height0 = 40.dp,
    height1 = 60.dp,
    height2 = 70.dp,
    height3 = 80.dp,
    height4 = 100.dp,
    height5 = 175.dp,
    heightBigTextInput = 180.dp,
    heightGraph = 200.dp,
    heightSummaryRow = 45.dp,
    heightSummaryScope = 230.dp,
    heightCard = 120.dp,
    heightPieChartInfo = 300.dp,
    heightBarChartInfo = 425.dp,
    heightHelp = 600.dp,
    //Image
    imageAboutMonth = 40.dp,
    imageMenuInput = 35.dp,
    imageLargeButton = 50.dp,
    image3 = 60.dp,
    image4 = 70.dp,
    imageSmallButton = 125.dp,
    //Width
    widthNone = 0.dp,
    widthBarChartInfo = 150.dp,
    widthAboutExchange = 125.dp,
    widthMediumButton = 200.dp,
    widthCard = 340.dp,
    widthCardColumn = 170.dp,
    widthInput = 380.dp,
    width6 = 250.dp,
    widthMessage = 400.dp,
    width8 = 470.dp,
    widthChartInfo = 525.dp,
    //Others
    rounded = 10.dp,
    shadow = 10.dp,
    border = 2.dp,
    //Space
    space0 = 10.dp,
    space1 = 15.dp,
    space2 = 20.dp,
    space3 = 25.dp,
    space4 = 50.dp,
    //FontSize
    fontSize0 = 27.sp,
    fontSize1 = 35.sp,
    fontSize2 = 35.sp,
    fontSize3 = 30.sp,
    fontSizeHeader = 34.sp,
    fontSizeTitle = 35.sp,
    fontSizeLogo = 48.sp,
    fontSizeSummaryRow = 25.sp,
    fontSizeMoney = 35.sp,
    fontSizeDate = 25.sp,
    fontSizeDescription = 25.sp,
    //Padding
    padding0 = 2.dp,
    padding1 = 7.dp,
    padding2 = 8.dp,
    padding3 = 10.dp,
    padding4 = 15.dp,
    padding5 = 20.dp,
    paddingHeaderFooter = 30.dp,
    //Size
    sizeLogoSmall = 175.dp,
    sizeLogoBig = 275.dp,
)

val LargeTablet = Dimens(
    //Height
    height0 = 50.dp,
    height1 = 65.dp,
    height2 = 75.dp,
    height3 = 80.dp,
    height4 = 100.dp,
    height5 = 175.dp,
    heightBigTextInput = 180.dp,
    heightGraph = 200.dp,
    heightSummaryScope = 300.dp,
    heightSummaryRow = 60.dp,
    heightCard = 120.dp,
    heightPieChartInfo = 300.dp,
    heightBarChartInfo = 550.dp,
    heightHelp = 750.dp,
    //Image
    imageAboutMonth = 50.dp,
    imageMenuInput = 35.dp,
    imageLargeButton = 50.dp,
    image3 = 65.dp,
    image4 = 75.dp,
    imageSmallButton = 150.dp,
    //Width
    widthNone = 0.dp,
    widthBarChartInfo = 160.dp,
    widthAboutExchange = 125.dp,
    widthMediumButton = 225.dp,
    widthCard = 360.dp,
    widthCardColumn = 180.dp,
    widthInput = 430.dp,
    width6 = 250.dp,
    widthMessage = 450.dp,
    width8 = 540.dp,
    widthChartInfo = 600.dp,
    //Others
    rounded = 10.dp,
    shadow = 10.dp,
    border = 2.dp,
    //Space
    space0 = 15.dp,
    space1 = 30.dp,
    space2 = 40.dp,
    space3 = 35.dp,
    space4 = 50.dp,
    //FontSize
    fontSize0 = 30.sp,
    fontSize1 = 37.sp,
    fontSize2 = 37.sp,
    fontSize3 = 35.sp,
    fontSizeHeader = 34.sp,
    fontSizeTitle = 45.sp,
    fontSizeLogo = 60.sp,
    fontSizeSummaryRow = 15.sp,
    fontSizeMoney = 40.sp,
    fontSizeDate = 25.sp,
    fontSizeDescription = 27.sp,
    //Padding
    padding0 = 2.dp,
    padding1 = 7.dp,
    padding2 = 8.dp,
    padding3 = 10.dp,
    padding4 = 15.dp,
    padding5 = 20.dp,
    paddingHeaderFooter = 30.dp,
    //Size
    sizeLogoSmall = 225.dp,
    sizeLogoBig = 300.dp,
)


